version: 2

cache_key: &cache_key
  key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "buildSrc/src/main/java/Deps.kt" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

jobs:
  check:
    working_directory: ~/basil
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          <<: *cache_key

      - run:
          name: Check
          command: ./gradlew check
      - store_artifacts:
          path: app/build/reports/lint-results.html
      - store_artifacts:
          path: app/build/reports/ktlint.xml

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

  deploy:
    working_directory: ~/basil
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          <<: *cache_key

      - run:
          name: Decrypt files
          command: bash enc/decrypt.sh
      - run:
          name: Publish APK
          command: ./gradlew publishApkRelease
      - run:
          name: Cleanup
          command: >-
              rm -f buildSrc/src/main/java/KeyStore.kt
              rm -f signing/release.keystore
              rm -f signing/play.json

workflows:
  version: 2
  check_deploy:
    jobs:
      - check
      - deploy:
         requires:
           - check
         filters:
           branches:
             only: master